//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSChina2020AppComp20.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponsorship
    {
        public int id { get; set; }
        public string name { get; set; }
        public string item { get; set; }
        public byte[] photo { get; set; }
        public int amount { get; set; }
        public int eventId { get; set; }
    
        public virtual Events Events { get; set; }
    }
}
