//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSChina2020AppComp20.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSkills
    {
        public int id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> SkillsId { get; set; }
        public string @event { get; set; }
    
        public virtual Skills Skills { get; set; }
        public virtual Users Users { get; set; }
    }
}
