//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSChina2020AppComp20.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSkills
    {
        public int id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> SkillsId { get; set; }
        public Nullable<int> eventId { get; set; }
    
        public virtual Events Events { get; set; }
        public virtual Skills Skills { get; set; }
        public virtual Users Users { get; set; }
    }
}
