//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSChina2020AppComp20.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Volunteers
    {
        public int id { get; set; }
        public string fullname { get; set; }
        public int genderId { get; set; }
        public int manageCityId { get; set; }
        public int cityId { get; set; }
        public int skillsId { get; set; }
        public int age { get; set; }
    
        public virtual City City { get; set; }
        public virtual Genders Genders { get; set; }
        public virtual Skills Skills { get; set; }
    }
}
